# キャラクタプロンプトテーブル
chara_tbl = {
    "博麗 霊夢": "hakurei reimu",
    "る～こと": "ruukoto,green hair,short hair,blue eyes,light blue maid apron,red bowtie,tareme",
    "カナ アナベラル": "kana anaberal",
    "魅魔": "mima \(touhou\)",
    "サニーミルク": "sunny milk",
    "ルナチャイルド": "luna child",
    "スターサファイア": "star sapphire",
    "北白河 ちゆり": "kitashirakawa chiyuri,naval uniform,blue neckerchief,sailor hat,crop top,shorts",
    "岡崎 夢美": "okazaki yumemi",
    "伊吹 萃香": "ibuki suika",
    "霧雨 魔理沙": "kirisame marisa",
    "ルーミア": "rumia",
    "大妖精": "daiyousei",
    "チルノ": "cirno",
    "十六夜 咲夜": "izayoi sakuya",
    "レミリア スカーレット": "remilia scarlet",
    "アリス マーガトロイド": "alice margatroid",
    "リリー ホワイト": "lily white",
    "リリー ブラック": "lily black",
    "リリカ プリズムリバー": "lyrica prismriver",
    "メルラン プリズムリバー": "merlin prismriver",
    "ルナサ プリズムリバー": "lunasa prismriver",
    "魂魄 妖夢": "konpaku youmu",
    "橙": "chen",
    "八雲 藍": "yakumo ran",
    "八雲 紫": "yakumo yukari",
    "リグル ナイトバグ": "wriggle nightbug",
    "ミスティア ローレライ": "mystia lorelei",
    "射命丸 文": "shameimaru aya",
    "四季 映姫": "shiki eiki",
    "東風谷 早苗": "kochiya sanae",
    "八坂 神奈子": "yasaka kanako",
    "洩矢 諏訪子": "moriya suwako",
    "比那名居 天子": "hinanawi tenshi",
    "永江 衣玖": "nagae iku",
    "火焔猫 燐": "kaenbyou rin",
    "霊烏路 空": "reiuji utsuho",
    "古明地 こいし": "komeiji koishi",
    "ナズーリン": "nazrin",
    "多々良 小傘": "tatara kogasa",
    "封獣 ぬえ": "houjuu nue",
    "姫海棠 はたて": "himekaidou hatate",
    "茨木 華扇": "ibaraki kasen",
    "ふわふわエレン": "ellen \(touhou\)",
    "朝倉 理香子": "asakura rikako,purple hair,long hair,purple eyes,round eyewear,white hair band,white hair ribbon,lab coat,yellow bowtie",
    "明羅": "meira \(touhou\),purple hair,long hair,ponytail,parted bangs,white ribbon",
    "里香": "rika \(touhou\),brown hair,twin braids,red ribbon,brown eyes,white shirt,long sleeves,red short necktie",
    "ルイズ": "louise \(touhou\),blonde hair,parted bangs,twintails,sidelocks,purple ribbon,white hat,white shirt,purple neckerchief,yellow eyes",
    "古明地 さとり": "komeiji satori",
    "フランドール": "flandre scarlet",
    "河城 にとり": "kawashiro nitori",
    "鈴仙・優曇華院・イナバ": "reisen udongein inaba",
    "因幡 てゐ": "inaba tewi",
    "パチュリー・ノーレッジ": "patchouli knowledge",
    "聖 白蓮": "hijiri byakuren",
    "豊聡耳神子": "toyosatomimi no miko",
    "秦こころ": "hata no kokoro",
    "紅美鈴": "hong meiling",
    "小悪魔": "koakuma",
    "水橋 パルスィ": "mizuhashi parsee",
    "藤原 妹紅": "fujiwara no mokou",
    "蓬莱山 輝夜": "houraisan kaguya",
    "今泉影狼": "imaizumi kagerou",
    "星熊 勇儀": "hoshiguma yuugi",
    "犬走 椛": "inubashiri momiji",
    "西行寺 幽々子": "saigyouji yuyuko",
    "上白沢 慧音": "kamishirasawa keine",
    "風見 幽香": "kazami yuuka",
    "二ッ岩 マミゾウ": "futatsuiwa mamizou",
    "本居 小鈴": "motoori kosuzu",
    "少名 針妙丸": "sukuna shinmyoumaru",
    "八意 永琳": "yagokoro eirin",
    "赤 蛮奇": "sekibanki",
    "レティ・ホワイトロック": "letty whiterock",
    "メディスン・メランコリー": "medicine melancholy",
    "小野塚 小町": "onozuka komachi",
    "秋 静葉": "aki shizuha",
    "秋 穣子": "aki minoriko",
    "鍵山 雛": "kagiyama hina",
    "稗田 阿求": "hieda no akyuu",
    "宇佐見 蓮子": "usami renko",
    "マエリベリー・ハーン": "maribel hearn",
    "キスメ": "kisume",
    "黒谷 ヤマメ": "kurodani yamame",
    "雲居 一輪": "kumoi ichirin",
    "村紗 水蜜": "murasa minamitsu",
    "寅丸 星": "toramaru shou",
    "幽谷 響子": "kasodani kyouko",
    "宮古 芳香": "miyako yoshika",
    "霍 青娥": "kaku seiga",
    "蘇我 屠自古": "soga no tojiko,ghost tail",
    "物部 布都": "mononobe no futo",
    "わかさぎ姫": "wakasagihime",
    "九十九 弁々": "tsukumo benben",
    "九十九 八橋": "tsukumo yatsuhashi",
    "堀川 雷鼓": "horikawa raiko",
    "鬼人 正邪": "kijin seija",
    "綿月 依姫": "watatsuki no yorihime",
    "綿月 豊姫": "watatsuki no toyohime",
    "レイセン": "reisen \(touhou bougetsushou\)",
    "朱鷺子": "tokiko \(touhou\)",
    "神綺": "shinki \(touhou\)",
    "夢子": "yumeko \(touhou\),yellow eyes,",
    "ユキ": "yuki \(touhou\),blonde hair,middle hair,yellow eyes,black hat,black clothes,white shirt,short sleeves,black skirt",
    "マイ": "mai \(touhou\),blue hair,blue eyes,short hair,light pink hair ribbon,white wings,light pink dress,",
    "宇佐見 菫子": "usami sumireko",
    "清蘭": "seiran \(touhou\)",
    "鈴瑚": "ringo \(touhou\)",
    "ドレミー・スイート": "doremy sweet",
    "稀神 サグメ": "kishin sagume",
    "クラウンピース": "clownpiece",
    "純狐": "junko \(touhou\)",
    "ヘカーティア・ラピスラズリ": "hecatia lapislazuli",
    "くるみ": "kurumi \(touhou\),blonde hair,long hair,yellow eyes,white ribbon,big bat wings",
    "エリー": "elly \(touhou\)",
    "夢月": "mugetsu \(touhou\)",
    "幻月": "gengetsu \(touhou\),white wings",
    "エタニティラルバ": "eternity larva",
    "坂田 ネムノ": "sakata nemuno,sharp teeth",
    "高麗野 あうん": "komano aunn",
    "矢田寺 成美": "yatadera narumi",
    "丁礼田 舞": "teireida mai",
    "爾子田 里乃": "nishida satono",
    "摩多羅 隠岐奈": "matara okina",
    "依神 女苑": "yorigami jo'on,tsurime",
    "依神 紫苑": "yorigami shion",
    "戎 瓔花": "ebisu eika",
    "牛崎 潤美": "ushizaki urumi",
    "庭渡 久侘歌": "niwatari kutaka",
    "吉弔 八千慧": "kicchou yachie",
    "杖刀偶 磨弓": "joutouguu mayumi",
    "埴安神 袿姫": "haniyasushin keiki",
    "驪駒 早鬼": "kurokoma saki",
    "奥野田 美宵": "okunoda miyoi",
    "豪徳寺 ミケ": "goutokuji mike",
    "山城 たかね,": "yamashiro takane",
    "駒草 山如": "komakusa sannyo",
    "玉造 魅須丸": "tamatsukuri misumaru",
    "菅牧 典": "kudamaki tsukasa",
    "飯綱丸 龍": "iizunamaru megumu",
    "天弓 千亦": "tenkyuu chimata",
    "姫虫 百々世": "himemushi momoyo",
    "饕餮 尤魔": "toutetsu yuuma,sharp teeth",
    "小兎姫": "kotohime \(touhou\),yellow ribbon",
    "エリス": "elis \(touhou\),yellow hair,long hair,red ribbon,red star on face,red hair flower,bat wings",
    "サリエル": "sariel \(touhou\),red eyes,white wings",
    "サラ": "sara \(touhou\),pink hair,side ponytail,short hair,red eyes,red frilled dress,white shirt,short sleeves",
    "オレンジ": "orange \(touhou\),orange hair,orange eyes,long hair,yellow shirt,yellow shorts,green skirt",
    "矜羯羅": "konngara \(touhou\)",
    "ユウゲンマガン": "yuugenmagan,blonde hair,ponytail,yellow eyes,white shirt,light yellow hakama",
    "キクリ": "kikuri \(touhou\),blonde hair,blue eyes,wavy hair,long hair,parted bangs",
    "孫 美天": "son biten",
    "三頭 慧ノ子": "mitsugashira enoko",
    "天火人 ちやり": "tenkajin chiyari",
    "豫母都 日狭美": "yomotsu hisami,flower over eyes",
    "日白 残無": "nippaku zanmu",
    "宮出口 瑞霊": "miyadeguchi mizuchi,blue hair,blue eyes,ponytail,crossed bangs,hair between eyes"
}